### ISSUE TITLE
Support TIF/GeoTIF in TUFLOW

### ISSUE THREAD

**Issue by saberraz** [TUFLOW-Support/QGIS-TUFLOW-Plugin#5]
It is not the right place to raise this, but is it possible to add support for TIF file in TGC. Working with ASCII grids are very slow in QGIS.

**Comment by itsgupta** [comment]
Hi, it has been over 5 years since this was posted. Is there any update to ease the integration of TIFs into TUFLOW. Perhaps as a downloadable add on if you do not wish to increase the size of the TUFLOW executable? @saberraz do you have any thoughts?

The TIF format is only 1 file which includes the projection as opposed to the .flt file which has a .hdr and .prj file too. If compression is supported, this will massively reduce the size of TUFLOW models. The current solution of converting a grid from TIF (Generated in QGIS) -> ASC (Convert / translate using GDAL) -> FLT (Convert using ASC to ASC)  is impractical and unnecessary in this day and age.

I dont think TUFLOW necessarily needs to output as TIF, just accepting it as an input format is sufficient. The adoption of FLT is basically nonexistent.

**Comment by TUFLOW-Support** [comment]
Hi, we are hoping to add additional vector and raster format support into the next major release of TUFLOW.

For any further TUFLOW related support, questions, or feature requests, please don't hesitate to email us at support@tuflow.com. This repository should be used for plugin related issues only.

Thanks,
Ellis
