### ISSUE TITLE
QGIS plugin bug - Python error 

### ISSUE THREAD

**Issue by jb0092** [TUFLOW-Support/QGIS-TUFLOW-Plugin#6]
Hey,

When I try to use the plugin to view my 1d results I get the following error after I try to load my results into the 1d viewer: 

![image](https://cloud.githubusercontent.com/assets/11188365/6365987/d9814552-bd0a-11e4-95b2-41c418e8ea1d.png)

I have recreated the scenario on a few computers. 
Thanks :)

**Comment by TUFLOW-Support** [comment]
Hi,

Thanks for pointing that out.  This issue is actually occurring in the latest 2013-12-AD version of TUFLOW.  In the .info file the link to the "_1d_Node.csv" and "_1d_Chan.csv" is incorrect.  The file is failing to open file:
Results\Design\csv\INN3_Q001_01hr_EC_Mit0_014_1d_Chan.csv

However, in the folder (Results\Design\csv\) you can see the file has been incorrectly written by TUFLOW as (note duplicate 1d_1d):
INN3_Q001_01hr_EC_Mit0_014_1d_1d_Chan.csv

This will need to be updated in the TUFLOW engine.  In the interim, there are a couple of options:
* rename the _1d_1d_Node.csv and _1d_1d_Chan.csv by removing extra "_1d".
* change the links in the .info file
Node Info == INN3_Q001_01hr_EC_Mit0_014_1d_1d_Node.csv
Channel Info == INN3_Q001_01hr_EC_Mit0_014_1d_1d_Chan.csv
* Use the 2013-12-AC version of TUFLOW.

When a update or new version of TUFLOW is released, this will be fixed.

Cheers
Phil

**Comment by TUFLOW-Support** [comment]
When using the 2015-05-AA or later version.  The incorrectly named file is checked for and updated.  This works around the issue above.

Cheers
Phil
